/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * ExpenditreViewDialog.java
 *
 * Created on Mar 20, 2013, 3:34:22 AM
 */
package vpsposclient;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;

/**
 *
 * @author Royal
 */
public class ExpenditureViewDialog extends javax.swing.JDialog {

    TableModel expenditureTableModel;
    static String expenditureDate;
    static String expenditure;
    static ArrayList<CashierExpendure> expenditureList = new ArrayList<CashierExpendure>();

    /** Creates new form ExpenditreViewDialog */
    public ExpenditureViewDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        expenditureTableModel = new Controller().cashierExpenditureTableModel(expenditureDate);
        initComponents();

        expenditureTable.setModel(expenditureTableModel);
        expenditureTable.setFont(new Font("serif", Font.PLAIN, 22));
        expenditureTable.setGridColor(new Color(252, 96, 17));
        expenditureTable.setRowMargin(3);
        expenditureTable.setRowHeight(40);
        expenditureTable.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        expenditureTable.getTableHeader().setFont(new Font("Serif", Font.BOLD, 18));
        expenditureTable.getTableHeader().setForeground(Color.BLUE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        expenditureTable = new javax.swing.JTable();
        add = new javax.swing.JButton();
        modify = new javax.swing.JButton();
        delete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        totalExpenditure = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        expenditureTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reason", "Amount", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(expenditureTable);
        expenditureTable.getColumnModel().getColumn(0).setResizable(false);
        expenditureTable.getColumnModel().getColumn(2).setResizable(false);

        add.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        add.setText("Add New Expenduture");
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        modify.setFont(new java.awt.Font("Times New Roman", 1, 14));
        modify.setText("Modify Expenditure");
        modify.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifyActionPerformed(evt);
            }
        });

        delete.setFont(new java.awt.Font("Times New Roman", 1, 14));
        delete.setText("Delete Expenditure");
        delete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24));
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("Total Expenditure");

        totalExpenditure.setBackground(new java.awt.Color(0, 0, 0));
        totalExpenditure.setFont(new java.awt.Font("Times New Roman", 1, 27));
        totalExpenditure.setForeground(new java.awt.Color(51, 255, 0));
        totalExpenditure.setText(expenditure);
        totalExpenditure.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(add)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(modify)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(delete))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel1)
                        .addGap(35, 35, 35)
                        .addComponent(totalExpenditure, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(modify)
                    .addComponent(delete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(totalExpenditure, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {add, delete, modify});

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
// TODO add your handling code here:
    ExpenditureDialog expenditureDialog = new ExpenditureDialog(Welcome.mainWindow, true);
    expenditureDialog.setTitle("Record Your Days Expenditure");
    expenditureDialog.setLocation(getWidth() / 4, getHeight() / 2);
    expenditureDialog.setVisible(true);
}//GEN-LAST:event_addActionPerformed

private void modifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifyActionPerformed
// TODO add your handling code here:
    ArrayList<String> list = new ArrayList<String>();
    try {
        int row = expenditureTable.getSelectedRow();
        String id = expenditureList.get(row).getCashierId();
        Object reason = expenditureTable.getModel().getValueAt(row, 0);
        Object amount = expenditureTable.getModel().getValueAt(row, 1);
        String date = (expenditureTable.getModel().getValueAt(row, 2)).toString();
        list = new Controller().dateTokens(date);

        UpdateExpenditureDialog.expenditureId = id;
        System.out.println(date);
        UpdateExpenditureDialog.amount = amount.toString();
        UpdateExpenditureDialog.reason = reason.toString();
        UpdateExpenditureDialog.currentDate = list.get(0);
        UpdateExpenditureDialog.currentMonth = list.get(1);
        UpdateExpenditureDialog.currentYear = list.get(2);
        UpdateExpenditureDialog updateExpenditureDialog = new UpdateExpenditureDialog(Welcome.mainWindow, true);
        updateExpenditureDialog.setTitle("Update Expenditure");
        updateExpenditureDialog.setLocation(getWidth() / 4, getHeight() / 5);
        updateExpenditureDialog.setVisible(true);

    } catch (Exception e) {
        System.out.println(e.getMessage());
        JOptionPane.showMessageDialog(null, "Nothing Selected");
        
    }


}//GEN-LAST:event_modifyActionPerformed

private void deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteActionPerformed
// TODO add your handling code here:
    try {
        int row = expenditureTable.getSelectedRow();
        String id = expenditureList.get(row).getCashierId();
        System.out.println(id);
        new Controller().deleteExpenditure(id, expenditureDate);
        ExpenditureViewDialog.totalExpenditure.setText(ExpenditureViewDialog.expenditure);
    } catch (Exception e) {
        System.out.println(e.getMessage());
        JOptionPane.showMessageDialog(null, "Nothing selected");
    }
}//GEN-LAST:event_deleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExpenditureViewDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExpenditureViewDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExpenditureViewDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExpenditureViewDialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                ExpenditureViewDialog dialog = new ExpenditureViewDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add;
    private javax.swing.JButton delete;
    public static javax.swing.JTable expenditureTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modify;
    public static javax.swing.JTextField totalExpenditure;
    // End of variables declaration//GEN-END:variables
}
