/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LoginWindow.java
 *
 * Created on Dec 2, 2012, 11:56:18 PM
 */
package vpsposclient;

import java.awt.Cursor;
import java.awt.event.KeyEvent;

/**
 *
 * @author royal
 */
public class LoginWindow extends javax.swing.JPanel {

    /** Creates new form LoginWindow */
    public LoginWindow() {
        initComponents();
        //userName.setBackground(Color.WHITE);
       /* userName.setRenderer(new DefaultListCellRenderer() {
        
        public Component getListCellRendererComponent(JList list, Object value, int index, boolean isSelected, boolean cellHasFocus) {
        
        final JLabel renderer = new JLabel(value.toString());
        if (isSelected) {
        renderer.setOpaque(true);
        renderer.setForeground(Color.BLUE);
        renderer.setBackground(Color.LIGHT_GRAY);
        }
        return renderer;
        }
        
        
        });*/

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        userName = new javax.swing.JComboBox();
        passWord = new javax.swing.JPasswordField();
        login = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("User Name");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 255));
        jLabel2.setText("PassWord");

        userName.setFont(new java.awt.Font("Times New Roman", 1, 18));
        userName.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Admin", "Cashier" }));
        userName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userNameMouseEntered(evt);
            }
        });
        userName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameActionPerformed(evt);
            }
        });
        userName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                userNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                userNameFocusLost(evt);
            }
        });
        userName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                userNameKeyPressed(evt);
            }
        });

        passWord.setFont(new java.awt.Font("Times New Roman", 1, 18));
        passWord.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        passWord.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                passWordKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                passWordKeyTyped(evt);
            }
        });

        login.setText("Login");
        login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vpsposclient/images/login.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(372, 372, 372)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(passWord, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(123, 123, 123)
                            .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(599, 599, 599))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {passWord, userName});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(passWord, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(login, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {passWord, userName});

    }// </editor-fold>//GEN-END:initComponents

private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
// TODO add your handling code here:
    try {
        String user = userName.getSelectedItem().toString();
        String pass = passWord.getText();
        boolean processing = true;
        do {
            login.setCursor(new Cursor(Cursor.WAIT_CURSOR));
            if (user.equalsIgnoreCase("admin")) {
                new Controller().initialise();
                new Controller().adminLogin(pass, user);
            } else if (user.equalsIgnoreCase("cashier")) {
                new Controller().initialise();
                new Controller().cashierLogin(pass, user);
            }
            processing = false;
        } while (processing == true);
        login.setCursor(new Cursor(Cursor.HAND_CURSOR));
    } catch (Exception ex) {
        System.out.println(ex.getMessage());
    }


}//GEN-LAST:event_loginActionPerformed

private void userNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_userNameActionPerformed

private void userNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameMouseEntered
// TODO add your handling code here:
}//GEN-LAST:event_userNameMouseEntered

private void userNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameFocusLost
// TODO add your handling code here:
}//GEN-LAST:event_userNameFocusLost

private void passWordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passWordKeyPressed
// TODO add your handling code here:
    try {
        boolean processing = true;
        do {
            
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                passWord.setCursor(new Cursor(Cursor.WAIT_CURSOR));
                this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
                loginActionPerformed(null);
            } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
                userName.requestFocus();
            }
            processing = false;
        } while (processing == true);
        passWord.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    } catch (Exception ex) {
        System.out.println(ex.getMessage());
    }
}//GEN-LAST:event_passWordKeyPressed

private void passWordKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passWordKeyTyped
// TODO add your handling code here:
    try {
        boolean processing = true;
        do {
            
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                passWord.setCursor(new Cursor(Cursor.WAIT_CURSOR));
                this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
                loginActionPerformed(null);
            } else if (evt.getKeyCode() == KeyEvent.VK_UP) {
                userName.requestFocus();
            }
            processing = false;
        } while (processing == true);
        passWord.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    } catch (Exception ex) {
        System.out.println(ex.getMessage());
    }
}//GEN-LAST:event_passWordKeyTyped

private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
// TODO add your handling code here:
}//GEN-LAST:event_formKeyPressed

private void userNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_userNameFocusGained
// TODO add your handling code here:
}//GEN-LAST:event_userNameFocusGained

private void userNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameKeyPressed
// TODO add your handling code here:

    try {
        boolean processing = true;
        do {
            
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                userName.setCursor(new Cursor(Cursor.WAIT_CURSOR));
                this.setCursor(new Cursor(Cursor.WAIT_CURSOR));
                loginActionPerformed(null);
            } else if (evt.getKeyCode() == KeyEvent.VK_DOWN) {
                passWord.requestFocus();
            }
            processing = false;
        } while (processing == true);
        userName.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
        this.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    } catch (Exception ex) {
        System.out.println(ex.getMessage());
    }
}//GEN-LAST:event_userNameKeyPressed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JButton login;
    private javax.swing.JPasswordField passWord;
    private javax.swing.JComboBox userName;
    // End of variables declaration//GEN-END:variables
}
